spring:
  profiles:
    active: dev
  application:
    name: http-utils

  #thymeleaf config
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

#the default size limit of upload files
#  http:
#    multipart:
#      enabled: true
#      max-file-size: 3MB
  servlet:
    multipart:
      max-file-size: 3MB
      enabled: true

# the default saved location of the upload files
file:
  storepath: ./webUploadFiles/

server:
  port: 9001
logging:
  level:
    com.briskhu.util.http: debug


---
spring:
  profiles: dev


