spring:
  profiles:
    active: dev

#\u4E0A\u4F20\u6587\u4EF6\u5927\u5C0F\u9650\u5236\u9ED8\u8BA4\u914D\u7F6E
http:
multipart:
enabled: true
max-file-size: 3MB

#\u4E0A\u4F20\u6587\u4EF6\u9ED8\u8BA4\u5B58\u50A8\u8DEF\u5F84\u914D\u7F6E
file:
storepath: ./clientUploadFiles/


---
spring:
  profiles: dev
    application:
      name: debugging-platform

  #thymeleaf\u914D\u7F6E
  thymeleaf:
    prefix: classpath:/static/htmlpages/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**