# \u6570\u636E\u5E93\u7BA1\u7406\u5DE5\u5177\u670D\u52A1\u7AEF(Web\u5B9E\u73B0)
server:
  port: 9918
  servlet:
    context-path: /dbadmin


#  springboot config
spring:
  application:
    name: DbAdminServer

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/?autoReconnect=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    username:
    password:
    minIdle: 5
    maxActive: 20
    initialSize: 5
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'ZTM' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    maxWait: 60000
#    open PSCache
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    filters: stat,wall,logback

  #thymeleaf配置
  thymeleaf:
    prefix: classpath:/static/template/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    com.briskhu: debug
#  config: classpath:config/





